### ISSUE TITLE
resort individuals according to original sequence

### ISSUE THREAD

**Issue by mastoffel** [mastoffel/GCalignR#2]

**Comment by mottensmann** [comment]
In align_chromatograms, line 309:
    gc_peak_list_aligned <- gc_peak_list_aligned[match(names(gc_peak_list_raw[names(gc_peak_list_aligned)]),names(gc_peak_list_aligned))]

This should do the job, but needs to be evaluted.

**Comment by mottensmann** [comment]
Line 311
Order is correct hereafter
    gc_peak_list_aligned <- gc_peak_list_aligned[match(names(gc_peak_list_raw),names(gc_peak_list_aligned))]

**Comment by mottensmann** [comment]
Fixed
