### ISSUE TITLE
Possible to speed up?

### ISSUE THREAD

**Issue by stanstrup** [mastoffel/GCalignR#25]
Hi,

I am trying to use your very interesting package on some LC-UV data (2 wavelengths).
It seems like it will be a very slow process with my 200 samples, though. I am trying with 4 test samples and so far after an hour it is at 15 %...

I assume the alignment of samples to the reference is an independent processes. In that case perhaps you could use `parallel::parSapply` to spread the work to all cores? If it is possible that should be an easy way to gain a lot of speed.

Cheers,
Jan.

**Comment by stanstrup** [comment]
I am probably using it wrong. I thought it was for aligning chromatograms, i.e. warping. Seems this aligns peaklists though. So that is the reason it was so slow for me when I fed it a whole chromatogram.

**Comment by mottensmann** [comment]
You are write the alignment is done using peak lists of all samples simultaneously. The alignment to the reference is only to account for systematic drift among GC runs and acutally not the time consuming step.
