### ISSUE TITLE
Error in code: choose_optimal_reference.R

### ISSUE THREAD

**Issue by hebertodelrio** [mastoffel/GCalignR#27]
In the file choose_optimal_reference.R on the line 47 inside the function choose_optimal_reference
it reads:

> index <- which(min(x[["score"]]/x[["n_peaks"]]) == min(x[["score"]]/x[["n_peaks"]]))

but I believe it should read:

> index <- which(x[["score"]]/x[["n_peaks"]] == min(x[["score"]]/x[["n_peaks"]]))

otherwise index will always contain 1

**Comment by mottensmann** [comment]
Many thanks for pointing out this error! I will update the code accordingly, and push a new release to GitHub and CRAN soon.
