### ISSUE TITLE
Checks in align_chromatograms 

### ISSUE THREAD

**Issue by mottensmann** [mastoffel/GCalignR#4]
Around line 182:

```
        if(any(duplicated(ind_names)))warning("Avoid duplications in sample names")
```

In order to avoid any ambiguity we should consider to prompt an error with stop()

**Comment by mastoffel** [comment]
yes. And in addition it would be perfect to check for weird symbols and spaces in the names, as these might cause errors later

**Comment by mottensmann** [comment]
Checks are implemented. Violations prompt warnings. Thereby the function does not end after detecting one issue, but shows all instead. Severe issues cause a failure in passing the complete check. This will be printed to the console and returned as a variable.
